export {default as CourtInfoTable} from './CourtInfoTable'
export {default as Bank100Infos} from './Bank100Infos'
export {default as TableComps} from './TableComps'
export {default as BaseInfo} from './BaseInfo'
export {default as PbankDetail} from './PbankDetail'
export {default as TongdunInfos} from './TongdunInfos'
export { getModuleConfig } from './moduleConfig'